# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'GuessWut' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Firebase
  pod 'Firebase', '= 3.6.0'
  pod 'Firebase/Messaging'

  # Facebook
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
end
